mode: deployment
image:
  repository: otel/opentelemetry-collector-k8s

command:
  name: otelcol-k8s

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ":4317"
        http:
          endpoint: ":4318"

  exporters:
    otlp:
      endpoint: "alloy.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [otlp]
