apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trace-test-app
  namespace: argocd
  labels:
    namespace: playground
spec:
  project: projectName
  source:
    repoURL: git@github.com:user/repo.git
    targetRevision: main
    path: clusters/dev/apps/playground/trace-test-app
  destination:
    server: https://kubernetes.default.svc
    namespace: playground
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
