apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    namespace: monitoring
spec:
  project: projectName
  source:
    repoURL: git@github.com:user/repo.git
    targetRevision: main
    path: clusters/dev/apps/monitoring/loki/chart
    helm:
      valueFiles:
        - ../values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
