apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-app-http
  namespace: playground
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: test-app
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
