apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: playground
  labels:
    app: test-app
spec:
  ports:
    - name: http-metrics
      port: 3000
      targetPort: 3000
  selector:
    app: test-app
