nameOverride: ""
fullnameOverride: ""
image:
  repository: "quay.io/sustainable_computing_io/kepler"
  tag: ""
  pullPolicy: Always
imagePullSecrets: []
annotations: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext:
  privileged: true
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
resources: {}
extraEnvVars:
  KEPLER_LOG_LEVEL: "1"
  ENABLE_GPU: "false"
  ENABLE_QAT: "false"
  ENABLE_EBPF_CGROUPID: "true"
  EXPOSE_HW_COUNTER_METRICS: "true"
  EXPOSE_IRQ_COUNTER_METRICS: "true"
  EXPOSE_CGROUP_METRICS: "false"
  ENABLE_PROCESS_METRICS: "false"
  CPU_ARCH_OVERRIDE: ""
  CGROUP_METRICS: '*'
canMount:
  usrSrc: true
service:
  annotations: {}
  type: ClusterIP
  port: 9102
rbac:
  create: true
serviceAccount:
  create: true
  annotations: {}
  name: ""
serviceMonitor:
  enabled: true
  namespace: ""
  interval: 30s
  scrapeTimeout: 5s
  labels:
    release: kube-prometheus-stack
  attachMetadata:
    node: false
  relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
        - __meta_kubernetes_pod_node_name
      targetLabel: instance
redfish:
  enabled: false
  name: redfish
  labels: {}
  annotations: {}
  fileContent: |-
    your_kubelet_node1_name,redfish_username,redfish_password,https://node1_redfish_ip_or_hostname
    your_kubelet_node2_name,redfish_username,redfish_password,https://node2_redfish_ip_or_hostname
