apiVersion: v1
kind: Service
metadata:
  name: trace-test-api-service
  namespace: playground
spec:
  selector:
    app: trace-test-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
